#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\e[92;1m"
YELL='\033[0;33m'
BGX="\033[42m"

grenbo="\e[92;1m"
NC='\033[0m'
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│$NC\033[42;9m           ADD BOTT MANAGER                $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
read -rp "      [*] BOT TOKEN      :  " -e bottoken 
read -rp "      [*] ID TELEGRAM  :  " -e admin
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
clear
echo -e ""
echo -e ""
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "                                    is Preparing Bot......." | lolcat
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
echo -e ""
sleep 3
if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/bot/${bottoken}
fi
DATADB=$(cat /etc/bot/.bot.db | grep "^#bot#" | grep -w "${bottoken}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/bot/.bot.db
fi
echo "#bot# ${bottoken} ${admin}" >>/etc/bot/.bot.db
clear 
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e " \e[1;97;101m      SUCCES ADD BOT NOTIFIKASI      \e[0m"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo " Bot Token      : $bottoken"
echo " ID Telegram  : $admin"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
read -n 1 -s -r -p "Press [ Enter ] to back menu"
menu