#!/bin/bash
DF='\e[39m'
RED='\033[0;31m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lyellow='\e[93m'
Lgreen='\e[92m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }

# Getting

REPO="https://raw.githubusercontent.com/arivpnstores/v2/main/bot/"

#satusbot
bot_kyt=$(systemctl status kyt | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
# STATUS SERVICE  BOT 
if [[ $bot_kyt == "running" ]]; then 
   status_bot="${GREEN}[ON]$NC${c} $NC"
else
   status_bot="${RED}[OFF]${NC} "
fi
#####
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/arivpnstores/v2/main/REGIST"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/ARI_VPN_STORE"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6281327393959"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 5
    reboot
  fi
}
checking_sc
# //
echo -e "\e[32mloading...\e[0m"
MYIP=$(wget -qO- ipinfo.io/ip);
# //
grenbo="\e[92;1m"
NC='\033[0m'
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│$NC\033[42m          MENU MANAGER BOT                $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;97m             STATUS BOTT : ${status_bot}"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[1;93m│  ${grenbo}1.${NC} \033[0;36mCREATE BOTT${NC}"
echo -e "\033[1;93m│  ${grenbo}2.${NC} \033[0;36mDELETE BOTT${NC}"
echo -e "\033[1;93m│  ${grenbo}3.${NC} \033[0;36mSTOPPP BOTT${NC}"
echo -e "\033[1;93m│  ${grenbo}4.${NC} \033[0;36mRESTAR BOTT${NC}"
echo -e "\033[1;93m│  ${grenbo}x.${NC} \033[0;36mCOMEBACK${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p " Select options >>    "  opt
echo -e   ""
case $opt in
01 | 1) clear ; wget ${REPO}bot.sh && chmod +x bot.sh && ./bot.sh ;;
02 | 2) clear ; hapus-bot ;;
02 | 3) clear ; stop-bot ;;
00 | 4) clear ; restart-bot ;;
*) clear ; menu ;;
esac
